# Basic configuration for GitHub Pages
name: CABO-FENWAY
title: Cape Verdean Night at Fenway Park
description: A special event celebrating Cape Verdean culture at Fenway Park

# GitHub Pages settings
url: "https://tmhsdigital.github.io"  # Replace with your GitHub Pages URL if different
baseurl: "/CABO-FENWAY"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

# Force HTTPS
enforce_ssl: tmhsdigital.github.io  # Replace with your custom domain if you have one
